// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-company-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var COMPANY = {
  name: "Thiesse Software",
  tagline: "Engenharia de software s\xEAnior para clientes nos EUA, na Europa e no setor p\xFAblico brasileiro.",
  headquarters: "Aracaju, Sergipe \u2014 Brasil",
  website: "https://thiesse.com.br",
  founders: ["Davi Thiesse"],
  focus_areas: [
    "Moderniza\xE7\xE3o de plataformas legadas",
    "Engenharia de software para o setor p\xFAblico",
    "Consultoria s\xEAnior para times globais",
    "Regulariza\xE7\xE3o Fundi\xE1ria Urbana (Reurb) \u2014 Governo de Sergipe"
  ],
  languages: ["pt-BR", "en", "es"]
};
var get_company_info_default = defineTool({
  name: "get_company_info",
  title: "Informa\xE7\xF5es da Thiesse Software",
  description: "Retorna informa\xE7\xF5es institucionais sobre a Thiesse Software: nome, sede, \xE1reas de atua\xE7\xE3o, fundadores e site.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(COMPANY, null, 2) }],
    structuredContent: COMPANY
  })
});

// src/lib/mcp/tools/list-clients.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var CLIENTS = [
  { name: "Governo de Sergipe", region: "Brasil", sector: "Setor p\xFAblico", project: "Regulariza\xE7\xE3o Fundi\xE1ria Urbana (Reurb)" },
  { name: "Clientes nos EUA", region: "Am\xE9rica do Norte", sector: "Tecnologia", project: "Consultoria e engenharia s\xEAnior" },
  { name: "Clientes na Europa", region: "Europa", sector: "Tecnologia", project: "Consultoria e engenharia s\xEAnior" }
];
var list_clients_default = defineTool2({
  name: "list_clients",
  title: "Listar clientes e parceiros",
  description: "Lista clientes e parceiros p\xFAblicos da Thiesse Software, incluindo regi\xE3o, setor e projeto associado.",
  inputSchema: {
    region: z.string().optional().describe("Filtro opcional por regi\xE3o (ex.: 'Brasil', 'Europa', 'Am\xE9rica do Norte').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ region }) => {
    const items = region ? CLIENTS.filter((c) => c.region.toLowerCase().includes(region.toLowerCase())) : CLIENTS;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { clients: items }
    };
  }
});

// src/lib/mcp/tools/list-experience.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var EXPERIENCE = [
  {
    title: "Parceria com o Governo de Sergipe \u2014 Reurb",
    summary: "Plataforma de Regulariza\xE7\xE3o Fundi\xE1ria Urbana desenvolvida em parceria com a SergipeTec para o Governo de Sergipe.",
    year_start: 2024
  },
  {
    title: "Consultoria s\xEAnior para clientes nos EUA e na Europa",
    summary: "Engenharia de software e lideran\xE7a t\xE9cnica para times distribu\xEDdos em produtos SaaS e plataformas de dados.",
    year_start: 2015
  },
  {
    title: "Funda\xE7\xE3o da Thiesse Software",
    summary: "Reposicionamento da atua\xE7\xE3o do fundador Davi Thiesse em uma empresa focada em engenharia s\xEAnior e setor p\xFAblico.",
    year_start: 2024
  }
];
var list_experience_default = defineTool3({
  name: "list_experience",
  title: "Hist\xF3rico e projetos",
  description: "Lista o hist\xF3rico e os principais projetos da Thiesse Software, incluindo a parceria com o Governo de Sergipe.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(EXPERIENCE, null, 2) }],
    structuredContent: { experience: EXPERIENCE }
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var CONTACT = {
  company: "Thiesse Software",
  location: "Aracaju, Sergipe \u2014 Brasil",
  website: "https://thiesse.com.br",
  linkedin: "https://linkedin.com/in/thiesse",
  note: "Para novas oportunidades e parcerias, entre em contato pelo LinkedIn ou pelo site."
};
var get_contact_default = defineTool4({
  name: "get_contact",
  title: "Informa\xE7\xF5es de contato",
  description: "Retorna canais p\xFAblicos de contato da Thiesse Software (site, LinkedIn e localiza\xE7\xE3o).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(CONTACT, null, 2) }],
    structuredContent: CONTACT
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "thiesse-software-mcp",
  title: "Thiesse Software MCP",
  version: "0.1.0",
  instructions: "Ferramentas p\xFAblicas do site institucional da Thiesse Software. Use para consultar informa\xE7\xF5es sobre a empresa, clientes, projetos (incluindo a parceria com o Governo de Sergipe para Reurb) e canais de contato.",
  tools: [get_company_info_default, list_clients_default, list_experience_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
